### ISSUE TITLE
Greg: ESC-ESC, ESC-ESC from routine editor should not abort save prompt

### ISSUE THREAD

**Issue by shabiel** [shabiel/VPE#29]
Right now, double escapes in a row will let you abort the save prompt, causing you to lose your changes.

**Comment by gkreis** [comment]
This happens when someone accidentally lays on the esc key (newbies mostly) and the key auto-repeat feature of the client software gets them out of the editor AND out of the save dialog. If the newbie does it once or twice (because they don't know what happened the first time) and the newbie could stop trying to learn VPE.

I feel this is a bug and needs to be resolved in the next release as it is extremely frustrating and bad PR for VPE.

It would seem the fix it to disable esc-esc as the means to exit the save dialog?
