### ISSUE TITLE
ESC-G should be re-implemented to use Block Mode

### ISSUE THREAD

**Issue by shabiel** [shabiel/VPE#30]
ESC-G should start the block, and ESC-G should close the block.

**Comment by gkreis** [comment]
I looked at this and I think it is smarter to have esc-G scan from the cursor BACK to the left until it sees the ^ of the global reference, rather than the cumbersome esc-G on the ^ and then again on the end position (which might be a comma to include one or more subscripts). That would be more like esc-R and the way it scans left if needed to pick up a line label.

Right now, it works with a single esc-G when on the ( of the reference, but it needs to work if on a comma which means to include the literal subscript (only meaningful for literal subscript(s)).

We would need to change the docs to explain the new approach.

**Comment by gkreis** [comment]
I really like the new implementation!

**Comment by shabiel** [comment]
Implemented in c6516a
